server:
  port: 11000
  error:
    path: /error
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/events
    username: root
    password: me@2020
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false